version: '3.8'
services:

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: roledb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot1234"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./role-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/roledb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./role-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
